name = "cloudflare-saas-starter"
compatibility_date = "2024-03-29"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "hactivist3-db"
database_id = "11eeca72-6ae8-4ec7-b26f-981e9b02098c"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "hactivist3"